### PR TITLE
Bug 1752351: UPSTREAM: 85293: Included FSType in CSI volumes

### PR DESCRIPTION
**Pull request by sallyom**
/assign @soltysh

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by huffmanca** [comment]
/retitle Bug 1752351: UPSTREAM: 85293: Included FSType in CSI volumes

**Comment by jsafrane** [comment]
Thanks for merging this!

Is BZ automation available here?

**Comment by soltysh** [comment]
@jsafrane I don't think so, you'll need to manually process this once we get the bump in openshift/oc repo.

**Pull request merged**
